# create smoke and critical tests

smoke:
  - name: Completeness check for dim_customers_scd table
    sql: "SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'bl_dm' AND TABLE_NAME = 'dim_customers_scd'"
    expected: 1
  - name: Completeness check for fct_taxi_trips table
    sql: "SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'bl_dm' AND TABLE_NAME = 'fct_taxi_trips'"
    expected: 1

critical:
  - name: Check 'dim_customers_scd' table has at least one row
    sql: "SELECT COUNT(*) FROM bl_dm.dim_customers_scd"
    expected: ">0"
  - name: Check no NULLs in trip_src_id
    sql: "SELECT COUNT(*) FROM bl_dm.fct_taxi_trips WHERE trip_src_id IS NULL"
    expected: 0


