name: checks

on:
  pull_request_target:
    types: [ opened, synchronize, reopened, labeled, unlabeled ]
    branches:
      - main

env:
  BRANCH: ${{github.head_ref}}

jobs:
  checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: checkout repository
        uses: actions/checkout@v3.5.3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: set up Miniconda with python version 3.9
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          channels: conda-forge
          activate-environment: python-course
          environment-file: environment.yml
          auto-activate-base: false
          python-version: 3.9

      - name: lint with flake8
        run:
          flake8 .

      - name: run tests
        run: |
          if [[ "$BRANCH" =~  ^Session_([1-9]) ]]; then
            pytest ./$BRANCH --tb=short
          fi
