# Configuration for pre-commit hooks, see: https://pre-commit.com/
default_language_version:
  python: python3.9
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=1024"]
        # 1 MB - Don't commit notebooks with output!
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/pycqa/isort
    rev: "5.12.0"
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/psf/black
    rev: "23.1.0"
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: "5.0.4"
    hooks:
      - id: flake8
